[project]
name = "pollux"
version = "0.1.0"
description = "A tool to recover and archive Google Gemini chat history from HAR files."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "markdownify>=1.2.2",
]

